### PR TITLE
Added BTC function

### PR DESCRIPTION
**Pull request by LeMoise**
Changed Ticker Variable to an Array to hold multiple values. This is used to store both the USD and BTC prices. 
Renames getRange to getUSDRange.
Added BTC Function to return BTC values.
Renumbered cells twice due to bad math.

### CODE REVIEW

**Comment by solifugo** [comment]
I like it.
Is there any way to call the function just once to get every coin Data?

I created few more functions and added 10 coins, so now I got this error:

https://github.com/saitei/crypto-sheets/issues/12
Service invoked too many times for one day: urlfetch

So, if we just call urlfetch once, should be better, but not sure if that is possible

**Comment by saitei** [comment]
@LeMoise Thanks for the additions.  I'd prefer to not make the getRate call specific to USD.  There's another branch called currency_conversion (saitei@94d487c5c0f960e3ce70961573ce89de2d58f090) where I'm working on better universal support for different fiat currencies.  The current API source (fixer.io) isn't great, so I'll probably leverage CMC's built in URL-based conversion ability.

@solifugo That's definitely the direction I'd like to go (a single API call with an array of values).  You could then possibly call getWebRate automatically for values not in the array.  The direction I'd like to go is having people simply put the ticket symbols in the spreadsheet and have the script do the rest of the work.  The next step would be creating a Sheets Add-On if it makes sense.

**Comment by apiontek** [comment]
As an aside, I want to work on a pull req for the following, any interest?

`getWebRate` doesn't seem necessary -- api endpoint seems able to take any currency id, I've tested several. It throws an error when currency id is unknown.

My proposal: modify `getRate` function as follows:

1. First, use the apiObj from my existing pull request
2. Check object for `currencyId` passed to function
3. If it's in the object, return rate from object, requires no additional URL fetch
4. If not in object, fetch api for specific currency (`"'.../ticker/' + currencyId"`)
5. Check if response is error (`"error": "id not found"`)
6. If no error, return rate from response
7. If error, use getWebRate function to return IMPORTXML string instead of parseFloat

I'm not sure if that last step would work, but if it doesn't I would work on using Xml.parse & XmlService to dig the rate out of the web request.

What do you think?

**Comment by saitei** [comment]
@apiontek  yeah, works for me.  I just had to use the web rate for when coins had just been added to CMC but not added to the API.  It should just be able to call the existing `getWebRate` function and split the value from the currency (which I had never gotten around to).  This could be paired with the array idea for a single API call.

Having people define the array cell the data is in is unfeasible though, so it should take a list of currencies the user wants (maybe from Rates!A) and grep the array for those values.  I considered just dumping the entire list into Rates but that would screw up references from other pages.

**Comment by solifugo** [comment]
This is what Im currently doing to get the coin list:

`  //Grabbing values from CoinMarketCapAPI
  //Setup your coins in the sheet Rates putting the names to match the 'id' field from https://api.coinmarketcap.com/v1/ticker/ in Column A Starting in Cell A2
  
  
  var Coin1 = ssRates.getRange('A2').getValue();
  var Coin2 = ssRates.getRange('A3').getValue();
  var Coin3 = ssRates.getRange('A4').getValue();
  var Coin4 = ssRates.getRange('A5').getValue();
  var Coin5 = ssRates.getRange('A6').getValue();
  var Coin6 = ssRates.getRange('A7').getValue();
  var Coin7 = ssRates.getRange('A8').getValue();
  var Coin8 = ssRates.getRange('A9').getValue();
  var Coin9 = ssRates.getRange('A10').getValue();
  var Coin10 = ssRates.getRange('A11').getValue();`


I have also added the Rates sheet titles:

`  // Set Rates sheet Titles
  
  ssRates.getRange('A1').setValue("Currency ID");
  ssRates.getRange('B1').setValue("Currency Name");
  ssRates.getRange('C1').setValue("Symbol");
  ssRates.getRange('D1').setValue("Price GBP");
  ssRates.getRange('E1').setValue("Change 1h");
  ssRates.getRange('F1').setValue("Change 24h");
  ssRates.getRange('G1').setValue("Change 7d");
  ssRates.getRange('H1').setValue("Last Updated UNIX");
  ssRates.getRange('I1').setValue("Last Updated Date");`

**Pull request closed without merging**
